### ISSUE TITLE
Time to live feature

### ISSUE THREAD

**Issue by inferrna** [dermesser/memoize#1]
Just implemented it for my purposes. Look on test1 - it's self-explainable ))
https://github.com/inferrna/memoize

**Comment by dermesser** [comment]
Very nice! Let me take a look :)

**Comment by dermesser** [comment]
I like it a lot and would definitely accept a pull request for this feature. Just one favor I'd ask for -- could you write a sentence or two about this feature in the README?

**Comment by inferrna** [comment]
After some thoughts I decided that using seconds as ttl is not rusty-way at all. And created another version - please, look also at ttl_as_duration branch where Duration is using instead of just seconds. If you ok with it, I'll create pull request with updated Readme.

**Comment by dermesser** [comment]
yes, looks good. Viscerally I liked SecondsToLive, but thinking that some applications may prefer sub-second TTLs, this is probably best.

**Comment by dermesser** [comment]
#2 has been merged and version 0.1.5 published to crates.io.
