### ISSUE TITLE
Panics when used on fn without args

### ISSUE THREAD

**Issue by jscheid** [dermesser/memoize#17]
```
$ cargo --version
cargo 1.64.0 (387270bc7 2022-09-16)
$ cargo init
$ cargo add memoize
$ printf 'use memoize::memoize;\n#[memoize]\nfn f() -> bool { true }' > src/main.rs
$ cargo build
error: custom attribute panicked
 --> src/main.rs:2:1
  |
2 | #[memoize]
  | ^^^^^^^^^^
  |
  = help: message: attempt to subtract with overflow
```

If you're not interested in supporting this use case, could at least the error message be improved?

**Comment by dermesser** [comment]
Hi! Sorry for the late reply. Indeed it is not super useful to support memoizing functions without arguments, but there is also no reason not to. I will look into improving the situation here.

**Comment by jscheid** [comment]
Ah awesome, thanks!

Maybe not super-duper useful but to me it would feel more elegant than `lazy_static`, at least syntactically. (I haven't worked out yet how it would differ in semantics.)
