### ISSUE TITLE
#[memoize] doesn't work on structs

### ISSUE THREAD

**Issue by GuiTaek** [dermesser/memoize#19]
Following Code:
```
use memoize::memoize;

struct Fib {
    counter: u32,
}

impl Fib {
    fn new() -> Self {
        Fib{counter: 0}
    }
    // #[memoize]
    fn calc(&mut self, n: u32) -> u32{
        self.counter += 1;
        if n == 0 || n == 1 {
            n
        } else {
            self.calc(n - 1) + self.calc(n - 2)
        }
    }
}

fn main() {
    let mut fib_calcer = Fib::new();
    println!("{}", fib_calcer.calc(3));
    println!("{}", fib_calcer.counter)
}
```
compiles, but this code:
```
use memoize::memoize;

struct Fib {
    counter: u32,
}

impl Fib {
    fn new() -> Self {
        Fib{counter: 0}
    }
    #[memoize]
    fn calc(&mut self, n: u32) -> u32{
        self.counter += 1;
        if n == 0 || n == 1 {
            n
        } else {
            self.calc(n - 1) + self.calc(n - 2)
        }
    }
}

fn main() {
    let mut fib_calcer = Fib::new();
    println!("{}", fib_calcer.calc(3));
    println!("{}", fib_calcer.counter)
}
```
doesn't compile. It says cannot memoize method (self-receiver) without arguments! I can't get the error, why exactly am I missing arguments?

**Comment by GuiTaek** [comment]
I have looked in your code and guess the problem is this part of code:

```
    if let syn::FnArg::Receiver(_) = sig.inputs[0] {
        return Err(syn::Error::new(
            sig.span(),
            "Cannot memoize method (self-receiver) without arguments!",
        ));
    }
```
in inner/src/lib.rs, line 344+
here, you ask, if the first element in the signature is self (that's probably what syn::FnArg::Receiver(_) means), then you raise an error. What in my opinion fits better is, to just ignore the first parameter (maybe configurable). If I find time, I will make a merge request, if that is OK for you!

**Comment by dermesser** [comment]
This has kind of been a known limitation, and it hasn't been important enough to fix. We cannot ignore the `self` parameter in any case, as a non-static method will almost always rely on it. If it didn't, the function could be extracted to global scope.

**Comment by GuiTaek** [comment]
Then maybe just change the error message so you just say, you don't allow
methods in general? I can also imagine having this configurable, so by
default it throws an error but you may turn this on (ignoring the state of
self).

Merry christmas, btw


Lewin Bormann ***@***.***> schrieb am Fr., 23. Dez. 2022,
19:34:

**Comment by dermesser** [comment]
Merry christmas to you, too! Yes, that's a good point. I will change this shortly.
