### ISSUE TITLE
SharedCache constraints?

### ISSUE THREAD

**Issue by melMass** [dermesser/memoize#26]
Hi,

Thanks for this lib, it works perfectly for my use case.
I'm now trying to add `SharedCache` but I'm getting the following error:

```ruby
no method named `with` found for struct `iconify::MEMOIZED_MAPPING_GET_INDEX` in the current scope
method not found in `MEMOIZED_MAPPING_GET_INDEX`
```

This is the signature of my `fn`:
```rust
#[memoize(SharedCache)]
pub fn get_index() -> Result<HashMap<String, IconSet>, String> {}
```

Thanks

**Comment by aminya** [comment]
I am having the same issue. It seems the bug was fixed, but not released on Crates.io.
@dermesser Could you release a new version?

**Comment by dermesser** [comment]
There have been no changes since 0.4.0, which is released. The original issue sounds like a naming conflict or similar.

**Comment by aminya** [comment]
Have you seen this pull request?
https://github.com/dermesser/memoize/pull/28

**Comment by dermesser** [comment]
Indeed I haven't, was looking at the wrong remote! Sorry.
