### ISSUE TITLE
Does not seem to work on recursive functions

### ISSUE THREAD

**Issue by FranklinChen** [dermesser/memoize#3]
My main use case for memoization is recursive algorithms (in place of bottom-up dynamic programming). Unfortunately, the following seems to hang:

```
use memoize::memoize;

#[memoize]
fn fib(n: u64) -> u64 {
    println!("calling fib of {}", n);
    if n == 0 || n == 1 {
        n
    } else {
        fib(n-2) + fib(n-1)
    }
}

fn main() {
    fib(5);
}
```

**Comment by dermesser** [comment]
Very good point. Stupid bug, because I missed this obvious use case.

**Comment by dermesser** [comment]
This is now published to crates.io as v0.1.6. Thank you for noticing this! I have also added an example with two recursive functions.

**Comment by FranklinChen** [comment]
Excellent!
