### ISSUE TITLE
Compiler warnings when using `mut` arguments

### ISSUE THREAD

**Issue by jhenninger** [dermesser/memoize#32]
I'm not sure if this is a issue with memoize or the Rust macro system in general. In the following example the Rust compiler will lie to you and claim that `foo` does not need to be mutable:

```rust
use memoize::memoize;

#[memoize]
fn expensive(mut foo: i32) -> i32 {
    foo += 1;
    foo
}

fn main() {
    expensive(7);
}
```

**Comment by dermesser** [comment]
yes, that's because the memoizer only ever reads from the variable. I've added an additional `allow()` to suppress this warning; to do it properly we'd need to update the function arguments (but that's fairly annoying, and nobody sees the generated code ever, anyway)
