### ISSUE TITLE
Memoize-inner wrong dependency version

### ISSUE THREAD

**Issue by Synar** [dermesser/memoize#34]
The [0.4.2 release version of memoize](https://crates.io/crates/memoize) on crates.io seems to use [the 0.4.0 version of memoize-inner](https://crates.io/crates/memoize-inner) instead of the correct 0.4.2 version. Features such as Ignore thus do not work on the current release.

**Comment by dermesser** [comment]
thank you for filing this issue, the dependency is set to "^0.4" - can you try running `cargo update`? This should update the dependency accordingly, given that we're only talking about a third-digit increase. Let me know if this works.

**Comment by FlorianGD** [comment]
Hi, I ran into the same issue. I did `cargo update`, but I still get `memoize-inner` set to `0.4.0`. It seems that the version `0.4.2` is not released to crates.io as the latest version I see is `0.4.0`: https://crates.io/crates/memoize-inner/versions/

Using the git version does work.

**Comment by dermesser** [comment]
Yes, you're right - for some reason I had missed that. I've release memoize-inner 0.4.3 just now
