### ISSUE TITLE
type paramaters

### ISSUE THREAD

**Issue by burdges** [dermesser/memoize#4]
It appears `'static` type parameters might be possible using [`std::any::TypeId`](https://doc.rust-lang.org/std/any/struct.TypeId.html), no?

**Comment by dermesser** [comment]
This is possible, do you have a concrete change in mind?

**Comment by burdges** [comment]
I have not looked into the macro code, so nothing really to propose.  There are enough variations here, ranging from `impl Trait` arguments, type parameters that only impact the return type, or even hashing non-static non-clone things, that often one should just run `cargo expand` on a simple example, and then customize it to anything strange.  Thanks!
